package bean;
// Generated 14/09/2023 09:09:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdutoNvb generated by hbm2java
 */
@Entity
@Table(name="produto_nvb"
    ,catalog="db_nathalia_boeira"
)
public class ProdutoNvb  implements java.io.Serializable {


     private int idprodutoNvb;
     private VendaProdutoNvb vendaProdutoNvb;
     private String nomeNvb;
     private String precoNvb;
     private String descontoNvb;
     private String freteNvb;

    public ProdutoNvb() {
    }

	
    public ProdutoNvb(int idprodutoNvb, VendaProdutoNvb vendaProdutoNvb) {
        this.idprodutoNvb = idprodutoNvb;
        this.vendaProdutoNvb = vendaProdutoNvb;
    }
    public ProdutoNvb(int idprodutoNvb, VendaProdutoNvb vendaProdutoNvb, String nomeNvb, String precoNvb, String descontoNvb, String freteNvb) {
       this.idprodutoNvb = idprodutoNvb;
       this.vendaProdutoNvb = vendaProdutoNvb;
       this.nomeNvb = nomeNvb;
       this.precoNvb = precoNvb;
       this.descontoNvb = descontoNvb;
       this.freteNvb = freteNvb;
    }
   
     @Id 

    
    @Column(name="idproduto_nvb", unique=true, nullable=false)
    public int getIdprodutoNvb() {
        return this.idprodutoNvb;
    }
    
    public void setIdprodutoNvb(int idprodutoNvb) {
        this.idprodutoNvb = idprodutoNvb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vendaProduto_nvb", nullable=false)
    public VendaProdutoNvb getVendaProdutoNvb() {
        return this.vendaProdutoNvb;
    }
    
    public void setVendaProdutoNvb(VendaProdutoNvb vendaProdutoNvb) {
        this.vendaProdutoNvb = vendaProdutoNvb;
    }

    
    @Column(name="nome_nvb", length=45)
    public String getNomeNvb() {
        return this.nomeNvb;
    }
    
    public void setNomeNvb(String nomeNvb) {
        this.nomeNvb = nomeNvb;
    }

    
    @Column(name="preco_nvb", length=45)
    public String getPrecoNvb() {
        return this.precoNvb;
    }
    
    public void setPrecoNvb(String precoNvb) {
        this.precoNvb = precoNvb;
    }

    
    @Column(name="desconto_nvb", length=45)
    public String getDescontoNvb() {
        return this.descontoNvb;
    }
    
    public void setDescontoNvb(String descontoNvb) {
        this.descontoNvb = descontoNvb;
    }

    
    @Column(name="frete_nvb", length=45)
    public String getFreteNvb() {
        return this.freteNvb;
    }
    
    public void setFreteNvb(String freteNvb) {
        this.freteNvb = freteNvb;
    }

}


