package bean;
// Generated 14/09/2023 09:09:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VendaProdutoNvb generated by hbm2java
 */
@Entity
@Table(name="vendaProduto_nvb"
    ,catalog="db_nathalia_boeira"
)
public class VendaProdutoNvb  implements java.io.Serializable {


     private int idvendaProdutoNvb;
     private ClienteNvb clienteNvb;
     private FuncionarioNvb funcionarioNvb;
     private String dataVendaNvb;
     private String valorNvb;
    

    public VendaProdutoNvb() {
    }

	
    public VendaProdutoNvb(int idvendaProdutoNvb, ClienteNvb clienteNvb, FuncionarioNvb funcionarioNvb) {
        this.idvendaProdutoNvb = idvendaProdutoNvb;
        this.clienteNvb = clienteNvb;
        this.funcionarioNvb = funcionarioNvb;
    }
    public VendaProdutoNvb(int idvendaProdutoNvb, ClienteNvb clienteNvb, FuncionarioNvb funcionarioNvb, String dataVendaNvb, String valorNvb) {
       this.idvendaProdutoNvb = idvendaProdutoNvb;
       this.clienteNvb = clienteNvb;
       this.funcionarioNvb = funcionarioNvb;
       this.dataVendaNvb = dataVendaNvb;
       this.valorNvb = valorNvb;
       
    }
   
     @Id 

    
    @Column(name="idvendaProduto_nvb", unique=true, nullable=false)
    public int getIdvendaProdutoNvb() {
        return this.idvendaProdutoNvb;
    }
    
    public void setIdvendaProdutoNvb(int idvendaProdutoNvb) {
        this.idvendaProdutoNvb = idvendaProdutoNvb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cliente_nvb", nullable=false)
    public ClienteNvb getClienteNvb() {
        return this.clienteNvb;
    }
    
    public void setClienteNvb(ClienteNvb clienteNvb) {
        this.clienteNvb = clienteNvb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_funcionario_nvb", nullable=false)
    public FuncionarioNvb getFuncionarioNvb() {
        return this.funcionarioNvb;
    }
    
    public void setFuncionarioNvb(FuncionarioNvb funcionarioNvb) {
        this.funcionarioNvb = funcionarioNvb;
    }

    
    @Column(name="dataVenda_nvb", length=45)
    public String getDataVendaNvb() {
        return this.dataVendaNvb;
    }
    
    public void setDataVendaNvb(String dataVendaNvb) {
        this.dataVendaNvb = dataVendaNvb;
    }

    
    @Column(name="valor_nvb", length=45)
    public String getValorNvb() {
        return this.valorNvb;
    }
    
    public void setValorNvb(String valorNvb) {
        this.valorNvb = valorNvb;
    }

}


