package bean;
// Generated 21/09/2023 14:09:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClienteVipNvb generated by hbm2java
 */
@Entity
@Table(name="cliente_Vip_nvb"
    ,catalog="db_nathalia_boeira"
)
public class ClienteVipNvb  implements java.io.Serializable {


     private int idclienteVipNvb;
     private String nomeNvb;
     private String dataNascimentoNvb;
     private String rgNvb;
     private String cpfNvb;
     private String sexoNvb;
     private String emailNvb;
     private String senhaNvb;
     private String telefoneNvb;
     private Set vendaProdutoNvbs = new HashSet(0);

    public ClienteVipNvb() {
    }

	
    public ClienteVipNvb(int idclienteVipNvb) {
        this.idclienteVipNvb = idclienteVipNvb;
    }
    public ClienteVipNvb(int idclienteVipNvb, String nomeNvb, String dataNascimentoNvb, String rgNvb, String cpfNvb, String sexoNvb, String emailNvb, String senhaNvb, String telefoneNvb, Set vendaProdutoNvbs) {
       this.idclienteVipNvb = idclienteVipNvb;
       this.nomeNvb = nomeNvb;
       this.dataNascimentoNvb = dataNascimentoNvb;
       this.rgNvb = rgNvb;
       this.cpfNvb = cpfNvb;
       this.sexoNvb = sexoNvb;
       this.emailNvb = emailNvb;
       this.senhaNvb = senhaNvb;
       this.telefoneNvb = telefoneNvb;
       this.vendaProdutoNvbs = vendaProdutoNvbs;
    }
   
     @Id 

    
    @Column(name="idcliente_Vip_nvb", unique=true, nullable=false)
    public int getIdclienteVipNvb() {
        return this.idclienteVipNvb;
    }
    
    public void setIdclienteVipNvb(int idclienteVipNvb) {
        this.idclienteVipNvb = idclienteVipNvb;
    }

    
    @Column(name="nome_nvb", length=45)
    public String getNomeNvb() {
        return this.nomeNvb;
    }
    
    public void setNomeNvb(String nomeNvb) {
        this.nomeNvb = nomeNvb;
    }

    
    @Column(name="dataNascimento_nvb", length=45)
    public String getDataNascimentoNvb() {
        return this.dataNascimentoNvb;
    }
    
    public void setDataNascimentoNvb(String dataNascimentoNvb) {
        this.dataNascimentoNvb = dataNascimentoNvb;
    }

    
    @Column(name="rg_nvb", length=45)
    public String getRgNvb() {
        return this.rgNvb;
    }
    
    public void setRgNvb(String rgNvb) {
        this.rgNvb = rgNvb;
    }

    
    @Column(name="cpf_nvb", length=45)
    public String getCpfNvb() {
        return this.cpfNvb;
    }
    
    public void setCpfNvb(String cpfNvb) {
        this.cpfNvb = cpfNvb;
    }

    
    @Column(name="sexo_nvb", length=45)
    public String getSexoNvb() {
        return this.sexoNvb;
    }
    
    public void setSexoNvb(String sexoNvb) {
        this.sexoNvb = sexoNvb;
    }

    
    @Column(name="email_nvb", length=45)
    public String getEmailNvb() {
        return this.emailNvb;
    }
    
    public void setEmailNvb(String emailNvb) {
        this.emailNvb = emailNvb;
    }

    
    @Column(name="senha_nvb", length=45)
    public String getSenhaNvb() {
        return this.senhaNvb;
    }
    
    public void setSenhaNvb(String senhaNvb) {
        this.senhaNvb = senhaNvb;
    }

    
    @Column(name="telefone_nvb", length=45)
    public String getTelefoneNvb() {
        return this.telefoneNvb;
    }
    
    public void setTelefoneNvb(String telefoneNvb) {
        this.telefoneNvb = telefoneNvb;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clienteVipNvb")
    public Set getVendaProdutoNvbs() {
        return this.vendaProdutoNvbs;
    }
    
    public void setVendaProdutoNvbs(Set vendaProdutoNvbs) {
        this.vendaProdutoNvbs = vendaProdutoNvbs;
    }
    public ClienteVipNvb getbean(int rowsel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setList(List lista) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }





}


