package bean;
// Generated 21/09/2023 14:09:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContaClienteNvb generated by hbm2java
 */
@Entity
@Table(name="contaCliente_nvb"
    ,catalog="db_nathalia_boeira"
)
public class ContaClienteNvb  implements java.io.Serializable {


     private int idcontaClienteNvb;
     private String nomeNvb;
     private String pedidosNvb;
     private String avaliacaoNvb;

    public ContaClienteNvb() {
    }

	
    public ContaClienteNvb(int idcontaClienteNvb) {
        this.idcontaClienteNvb = idcontaClienteNvb;
    }
    public ContaClienteNvb(int idcontaClienteNvb, String nomeNvb, String pedidosNvb, String avaliacaoNvb) {
       this.idcontaClienteNvb = idcontaClienteNvb;
       this.nomeNvb = nomeNvb;
       this.pedidosNvb = pedidosNvb;
       this.avaliacaoNvb = avaliacaoNvb;
    }
   
     @Id 

    
    @Column(name="idcontaCliente_nvb", unique=true, nullable=false)
    public int getIdcontaClienteNvb() {
        return this.idcontaClienteNvb;
    }
    
    public void setIdcontaClienteNvb(int idcontaClienteNvb) {
        this.idcontaClienteNvb = idcontaClienteNvb;
    }

    
    @Column(name="nome_nvb", length=50)
    public String getNomeNvb() {
        return this.nomeNvb;
    }
    
    public void setNomeNvb(String nomeNvb) {
        this.nomeNvb = nomeNvb;
    }

    
    @Column(name="pedidos_nvb", length=450)
    public String getPedidosNvb() {
        return this.pedidosNvb;
    }
    
    public void setPedidosNvb(String pedidosNvb) {
        this.pedidosNvb = pedidosNvb;
    }

    
    @Column(name="avaliacao_nvb", length=100)
    public String getAvaliacaoNvb() {
        return this.avaliacaoNvb;
    }
    
    public void setAvaliacaoNvb(String avaliacaoNvb) {
        this.avaliacaoNvb = avaliacaoNvb;
    }




}


